Repository WISEiTECH-SW/WISE-Office, pull requests merged in 2025-08, with the labels that each got.

#1 [DOCUMENT] 이슈 템플릿 및 리포지터리 구성
  .github/ISSUE_TEMPLATE/버그-및-에러-등록.md
  .github/ISSUE_TEMPLATE/이슈-등록.md
  .github/PULL_REQUEST_TEMPLATE.md
  wise-office-client/README.md
  wise-office-infra/README.md
  wise-office-server/README.md
Labels: documentation

#4 [FEATURE] 백오피스 서비스 클라이언트 개발환경 구성
  wise-office-client/.gitignore
  wise-office-client/eslint.config.mjs
  wise-office-client/next.config.ts
  wise-office-client/package-lock.json
  wise-office-client/package.json
  wise-office-client/postcss.config.mjs
  wise-office-client/public/file.svg
  wise-office-client/public/globe.svg
  wise-office-client/public/next.svg
  wise-office-client/public/vercel.svg
  wise-office-client/public/window.svg
  wise-office-client/src/app/favicon.ico
  wise-office-client/src/app/globals.css
  wise-office-client/src/app/layout.tsx
  wise-office-client/src/app/page.tsx
  wise-office-client/tsconfig.json
Labels: enhancement

#7 [FEATURE] 백오피스 서비스 서버 개발환경 구성
  wise-office-infra/dev-env.bat
  wise-office-infra/docker-compose.yml
  wise-office-server/.gitattributes
  wise-office-server/.gitignore
  wise-office-server/Dockerfile
  wise-office-server/backend-run.bat
  wise-office-server/backend-stop.bat
  wise-office-server/build.gradle
  wise-office-server/gradle/wrapper/gradle-wrapper.jar
  wise-office-server/gradlew
  wise-office-server/gradlew.bat
  wise-office-server/settings.gradle
  wise-office-server/src/main/java/kr/co/wise/office/BackofficeApplication.java
  wise-office-server/src/main/java/kr/co/wise/office/TestController.java
  wise-office-server/src/main/java/kr/co/wise/office/config/SecurityConfig.java
  wise-office-server/src/main/java/kr/co/wise/office/config/SwaggerConfig.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Log/entity/LogEntity.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Project/entity/ProjectEntity.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/attendant/entity/AttendantEntity.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/comment/entity/CommentEntity.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/member/entity/MemberEntity.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/member/entity/MemberRoleType.java
  wise-office-server/src/test/java/kr/co/wise/office/BackofficeApplicationTests.java
Labels: enhancement

#13 [FEATURE] 백엔드 서버 구글 Oauth2 로그인 인증 구현
  wise-office-server/build.gradle
  wise-office-server/src/main/java/kr/co/wise/office/api/HealthCheckController.java
  wise-office-server/src/main/java/kr/co/wise/office/config/JpaAuditingConfig.java
  wise-office-server/src/main/java/kr/co/wise/office/config/JwtConfigProp.java
  wise-office-server/src/main/java/kr/co/wise/office/config/SecurityConfig.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/member/dto/CustomOAuthUser.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/member/entity/MemberEntity.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/member/repository/MemberRepository.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/member/service/MemberService.java
  wise-office-server/src/main/java/kr/co/wise/office/security/filter/JWTFilter.java
  wise-office-server/src/main/java/kr/co/wise/office/security/handler/OAuth2SuccessHandler.java
  wise-office-server/src/main/java/kr/co/wise/office/util/JWTUtil.java
Labels: enhancement

#16 [FEATURE] 구글 로그인 버튼 추가 및 OAUth 플로우 연동
  wise-office-client/public/assets/Google.png
  wise-office-client/src/components/LoginButton.tsx
  wise-office-client/src/pages/_app.tsx
Labels: enhancement

#32 [FEATURE] Log 작성 모달창 구현
  wise-office-client/src/components/project/ProjectLog.tsx
  wise-office-client/src/components/project/ProjectLogDetail.tsx
  wise-office-client/src/components/project/ProjectLogInput.tsx
  wise-office-client/src/components/project/index.ts
  wise-office-client/src/components/project/types.ts
  wise-office-client/src/pages/project.tsx
Labels: enhancement

#33 [FEATURE] 어카운트 페이지 화면 구현
  wise-office-client/src/components/account/MyInfo.tsx
  wise-office-client/src/components/account/ProjectCardsMy.tsx
  wise-office-client/src/components/account/UserProfile.tsx
  wise-office-client/src/pages/account.tsx
Labels: enhancement

#41 [REFACTOR] 마이페이지 수정사항 반영
  wise-office-client/src/components/account/ProjectCardsMy.tsx
  wise-office-client/src/components/account/UserProfile.tsx
  wise-office-client/src/pages/account.tsx
Labels: enhancement

#39 [FEATURE] 로그 CRUD API 구현
  wise-office-infra/docker-compose.yml
  wise-office-server/src/main/java/kr/co/wise/office/api/LogController.java
  wise-office-server/src/main/java/kr/co/wise/office/api/ProjectController.java
  wise-office-server/src/main/java/kr/co/wise/office/application/LogServiceApi.java
  wise-office-server/src/main/java/kr/co/wise/office/application/ProjectServiceApi.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Log/dto/LogCreateRequest.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Log/dto/LogCreateResponse.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Log/dto/LogDetailResponse.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Log/dto/LogListResponse.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Log/dto/LogUpdateRequest.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Log/dto/LogUpdateResponse.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Log/entity/LogEntity.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Log/repository/LogRepository.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Log/service/LogService.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Project/Service/ProjectService.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Project/dto/ProjectDetailResponse.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Project/repository/ProjectRepository.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/attendant/dto/AttendantDetail.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/attendant/repository/AttendantRepository.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/attendant/service/AttendantService.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/comment/repository/CommentRepository.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/comment/service/CommentService.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/member/service/MemberService.java
  wise-office-server/src/main/java/kr/co/wise/office/exception/ErrorMessage.java
  wise-office-server/src/main/java/kr/co/wise/office/exception/custom/ApplicationRuntimeException.java
  wise-office-server/src/main/java/kr/co/wise/office/exception/custom/NotFoundResourceException.java
  wise-office-server/src/main/java/kr/co/wise/office/exception/custom/UnAuthorizationException.java
  wise-office-server/src/main/java/kr/co/wise/office/exception/dto/ErrorResponse.java
  wise-office-server/src/main/java/kr/co/wise/office/exception/handler/GlobalExceptionHandler.java
Labels: enhancement

#38 [FEATURE] project 페이지 퍼블리싱
  wise-office-client/src/api/project.ts
  wise-office-client/src/components/ProjectListCard.tsx
  wise-office-client/src/components/project/ProjectAttendantItem.tsx
  wise-office-client/src/components/project/ProjectAttendantList.tsx
  wise-office-client/src/components/project/ProjectInfoContainer.tsx
  wise-office-client/src/components/project/ProjectInfoItem.tsx
  wise-office-client/src/components/project/index.ts
  wise-office-client/src/lib/clientApi.ts
  wise-office-client/src/lib/common/util.ts
  wise-office-client/src/pages/project_old.tsx
  wise-office-client/src/pages/projects/[id].tsx
  wise-office-client/src/services/projects.ts
  wise-office-client/src/types/project.ts
Labels: enhancement

#46 [ERROR / BUG] util 함수 공통 사용 오류 수정
  wise-office-client/src/components/ProjectListCard.tsx
  wise-office-client/src/components/account/ProjectCardsMy.tsx
  wise-office-client/src/components/project/ProjectInfoContainer.tsx
  wise-office-client/src/lib/clientApi.ts
  wise-office-client/src/lib/common/util.ts
Labels: bug

#50 [FEATURE] 토스트 팝업 추가
  wise-office-client/next.config.ts
  wise-office-client/package-lock.json
  wise-office-client/package.json
  wise-office-client/src/components/header/LogoutButton.tsx
  wise-office-client/src/components/header/Profile.tsx
  wise-office-client/src/hooks/useInitAuth.ts
  wise-office-client/src/hooks/useLoginToast.ts
  wise-office-client/src/hooks/useRouteGuard.ts
  wise-office-client/src/lib/common/readLoggedIn.ts
  wise-office-client/src/lib/common/toastMessage.ts
  wise-office-client/src/lib/util.ts
  wise-office-client/src/middleware.ts
  wise-office-client/src/pages/_app.tsx
  wise-office-client/src/pages/index.tsx
  wise-office-client/src/pages/middleware.ts
  wise-office-client/src/store/useAuthStore.ts
Labels: enhancement

#56 [FEATURE] 헤더 디자인 개선
  wise-office-client/public/assets/logo.png
  wise-office-client/public/favicon.ico
  wise-office-client/public/favicon.png
  wise-office-client/public/logo.png
  wise-office-client/src/components/header/LoginButton.tsx
  wise-office-client/src/lib/common/toastMessage.ts
  wise-office-client/src/lib/project/info.ts
  wise-office-client/src/pages/_app.tsx
  wise-office-client/src/pages/account.tsx
  wise-office-client/src/pages/api/members.ts
  wise-office-client/src/pages/api/members/me.ts
  wise-office-client/src/pages/api/projects.ts
  wise-office-client/src/pages/api/v2/projects.ts
  wise-office-client/src/pages/project_modal.tsx
  wise-office-client/src/services/projects.ts
Labels: enhancement

#59 [FEATURE] 프로젝트 생성 시 동작 개선
  wise-office-client/src/pages/index.tsx
  wise-office-client/src/pages/project_modal.tsx
  wise-office-client/src/store/useProjects.ts
Labels: enhancement

#60 [FEATURE] Validation 검증 코드 작성
  wise-office-server/src/main/java/kr/co/wise/office/api/CommentController.java
  wise-office-server/src/main/java/kr/co/wise/office/api/LogController.java
  wise-office-server/src/main/java/kr/co/wise/office/api/MemberController.java
  wise-office-server/src/main/java/kr/co/wise/office/api/ProjectControllerV2.java
  wise-office-server/src/main/java/kr/co/wise/office/api/validation/annotation/ValidDateRange.java
  wise-office-server/src/main/java/kr/co/wise/office/api/validation/validator/ProjectPeriodValidator/ProjectCreatePeriodValidator.java
  wise-office-server/src/main/java/kr/co/wise/office/api/validation/validator/ProjectPeriodValidator/ProjectUpdatePeriodValidator.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Log/dto/LogCreateRequest.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Log/dto/LogUpdateRequest.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Log/dto/LogUpdateResponse.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Project/Service/ProjectService.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Project/dto/ProjectCreateRequest.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/Project/dto/ProjectUpdateRequest.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/comment/dto/CommentCreateRequest.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/comment/dto/CommentUpdateRequest.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/member/dto/MemberPositionUpdateRequest.java
  wise-office-server/src/main/java/kr/co/wise/office/exception/dto/ErrorResponse.java
  wise-office-server/src/main/java/kr/co/wise/office/exception/handler/GlobalExceptionHandler.java
Labels: enhancement

#63 [FEATURE] 프로젝트 생성 시 폼 오류 토스트 팝업 추가
  wise-office-client/src/components/header/Profile.tsx
  wise-office-client/src/components/project/ProjectAttendantItem.tsx
  wise-office-client/src/components/project/ProjectAttendantList.tsx
  wise-office-client/src/pages/project_modal.tsx
  wise-office-client/src/types/project.ts
Labels: enhancement

#64 [FEATURE] project 페이지 퍼블리싱
  wise-office-client/package-lock.json
  wise-office-client/package.json
  wise-office-client/src/components/project/ProjectCommentList.tsx
  wise-office-client/src/components/project/ProjectCommentListItem.tsx
  wise-office-client/src/components/project/ProjectLog.tsx
  wise-office-client/src/components/project/ProjectLogDetail.tsx
  wise-office-client/src/components/project/ProjectLogItem.tsx
  wise-office-client/src/components/project/index.ts
  wise-office-client/src/components/project/types.ts
  wise-office-client/src/lib/common/util.ts
  wise-office-client/src/lib/project/comment.ts
  wise-office-client/src/lib/project/log.ts
  wise-office-client/src/pages/project_old.tsx
  wise-office-client/src/pages/projects/[id].tsx
  wise-office-client/src/services/coments.ts
  wise-office-client/src/services/logs.ts
  wise-office-client/src/types/comment.ts
  wise-office-client/src/types/log.ts
  wise-office-server/src/main/java/kr/co/wise/office/api/CommentController.java
  wise-office-server/src/main/java/kr/co/wise/office/application/CommentServiceApi.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/comment/service/CommentService.java
Labels: enhancement

#78 [ERROR / BUG] ADMIN 계정 프로젝트 수정/삭제 버그
  wise-office-server/src/main/java/kr/co/wise/office/application/ProjectServiceApiV2.java
  wise-office-server/src/main/java/kr/co/wise/office/domain/attendant/service/AttendantService.java
Labels: bug

#82 [ERROR / BUG] 프로젝트 수정&삭제 모달
  wise-office-client/src/components/project/SelectProjectMembers.tsx
  wise-office-client/src/components/project/project_modal.tsx
  wise-office-client/src/components/project/project_modal_update.tsx
  wise-office-client/src/pages/index.tsx
  wise-office-client/src/pages/projects/[id].tsx
  wise-office-client/src/services/projects.ts
  wise-office-server/src/main/java/kr/co/wise/office/api/ProjectControllerV2.java
Labels: bug
